[package]
name = "xee-format"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ibig = "0.3.6"
icu = { version = "1.3.2", features = ["compiled_data"] }
num-traits = "0.2.16"
